# Generated by Django 5.1.6 on 2025-02-13 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Admin', 'Admin'), ('HR', 'HR'), ('Accountant', 'Accountant'), ('Employee', 'Employee')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('province', models.CharField(choices=[('Central', 'Central'), ('Copperbelt', 'Copperbelt'), ('Eastern', 'Eastern'), ('Luapula', 'Luapula'), ('Lusaka', 'Lusaka'), ('Muchinga', 'Muchinga'), ('Northern', 'Northern'), ('North-Western', 'North-Western'), ('Southern', 'Southern'), ('Western', 'Western')], max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('work_type', models.CharField(choices=[('full-time', 'Full-Time'), ('part-time', 'Part-Time'), ('freelance', 'Freelance'), ('internship', 'Internship')], max_length=20)),
                ('department', models.CharField(choices=[('hr', 'Human Resources'), ('it', 'Information Technology'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('finance', 'Finance'), ('engineering', 'Engineering')], max_length=50)),
                ('position', models.CharField(choices=[('manager', 'Manager'), ('developer', 'Developer'), ('designer', 'Designer'), ('analyst', 'Analyst'), ('executive', 'Executive'), ('assistant', 'Assistant'), ('intern', 'Intern')], max_length=50)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('identification_type', models.CharField(choices=[('nrc', 'National Registration Card (NRC)'), ('passport', 'Passport')], max_length=20)),
                ('identification_number', models.CharField(max_length=50, unique=True)),
                ('id_front', models.ImageField(upload_to='employee_ids/fronts/')),
                ('id_back', models.ImageField(upload_to='employee_ids/backs/')),
                ('nhima_number', models.CharField(max_length=20, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('roles', models.ManyToManyField(related_name='employees', to='base.role')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leave_type', models.CharField(choices=[('Annual Leave', 'Annual Leave'), ('Sick Leave', 'Sick Leave'), ('Maternity Leave', 'Maternity Leave'), ('Paternity Leave', 'Paternity Leave'), ('Study Leave', 'Study Leave'), ('Compassionate Leave', 'Compassionate Leave'), ('Unpaid Leave', 'Unpaid Leave')], max_length=50)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveCommutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_to_sell', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryAdvanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_needed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('requested_on', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
    ]
