# Generated by Django 5.1.6 on 2025-02-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('hr', 'Human Resources'), ('it', 'Information Technology'), ('sales/marketing', 'sales/marketing'), ('finance', 'Finance'), ('engineering', 'Engineering')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('Admin', 'Admin'), ('TDR', 'TDR'), ('developer-snr', 'developer-snr'), ('developer-jrn', 'developer-jrn'), ('developer-intern', 'developer-intern'), ('accountant', 'accountant')], max_length=50),
        ),
    ]
