# Generated by Django 5.1.6 on 2025-02-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_employee_department_alter_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Admin', 'Admin'), ('HR', 'HR'), ('Accountant', 'Accountant'), ('Employee', 'Employee')], default='Employee', max_length=20, unique=True),
        ),
    ]
