# Generated by Django 5.1.6 on 2025-02-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ss_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='t_pin',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
