# Generated by Django 5.1.6 on 2025-02-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_employee_ss_number_employee_t_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='identification_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='identification_type',
            field=models.CharField(blank=True, choices=[('nrc', 'National Registration Card (NRC)'), ('passport', 'Passport')], max_length=20, null=True),
        ),
    ]
