# Generated by Django 5.1.6 on 2025-02-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_employee_identification_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('hr', 'Human Resources'), ('it', 'Information Technology'), ('sales/marketing', 'Sales/Marketing'), ('finance', 'Finance'), ('engineering', 'Engineering')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('Admin', 'Admin'), ('TDR', 'TDR'), ('developer-snr', 'Developer (Senior)'), ('developer-jrn', 'Developer (Junior)'), ('developer-intern', 'Developer (Intern)'), ('accountant', 'Accountant')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='roles',
            field=models.ManyToManyField(blank=True, to='base.role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Admin', 'Admin'), ('HR', 'HR'), ('Accountant', 'Accountant'), ('Employee', 'Employee')], default='Employee', max_length=20),
        ),
    ]
