# Generated by Django 5.1.6 on 2025-02-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_employee_roles_role_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavecommutation',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='salaryadvancerequest',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='employees', to='base.role'),
        ),
        migrations.DeleteModel(
            name='LeaveApplication',
        ),
        migrations.DeleteModel(
            name='LeaveCommutation',
        ),
        migrations.DeleteModel(
            name='SalaryAdvanceRequest',
        ),
    ]
