# Generated by Django 5.1.6 on 2025-02-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_leaveapplication_leavecommutation_salaryadvance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ss_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='t_pin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
