# Generated by Django 5.1.6 on 2025-02-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_employee_ss_number_alter_employee_t_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='nhima_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
