# Generated by Django 5.1.6 on 2025-02-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_employee_nhima_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='identification_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
