# Generated by Django 5.1.6 on 2025-02-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_employee_identification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('Human Resources', 'Human Resources'), ('Information Technology', 'Information Technology'), ('sales/marketing', 'Sales/Marketing'), ('Finance', 'Finance'), ('Engineering', 'Engineering')], max_length=50),
        ),
    ]
