# Generated by Django 5.1.6 on 2025-02-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
