# Generated by Django 5.1.6 on 2025-02-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_permission_remove_employee_roles_employee_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryadvance',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
