# Generated by Django 5.1.6 on 2025-02-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_salaryadvance_repayment_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='employee_profile/pics'),
        ),
    ]
